server:
  port: 8080
  servlet:
    context-path: /api/


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 1123
  liquibase:
    change-log: classpath:db/db.changelog-root.xml
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

app:
  security:
    auth:
      secret: I05hWEQ0ZWFAZGY3JHF3RCEyNmkwZUIqamFqbmRzYUFMU2E=
      access-token-expiration-ms: 3600000
      refresh-token-expiration-ms: 86400000
